"""A fake ``MetaTrader5`` module for unit tests.

The real package works only on Windows with a running, logged-in terminal. Everything the
loader (and later the broker adapter) touches is reproduced here with the same names, the
same return shapes and the same conventions, so a test can pass a :class:`FakeMT5` instance
wherever the code takes an ``mt5`` module:

- ``copy_rates_range`` returns a NumPy structured array with the real field names and
  dtypes (``time`` is epoch seconds on the *server* clock read as if it were UTC);
- ``symbol_info`` returns an object with ``trade_contract_size``, ``volume_min``,
  ``volume_step``, ``volume_max``, ``digits``, ``point``, ``swap_long``, ``swap_short``,
  ``swap_rollover3days``, ``trade_mode`` and ``path``;
- ``symbol_info_tick`` returns ``time``, ``bid``, ``ask`` where ``time`` is the server clock;
- ``copy_ticks_range`` returns a ``TICKS_DTYPE`` array from ``fake.ticks[name]`` (see
  :func:`synthetic_ticks`), the shape ``bots._shared.costs_mt5`` reads;
- ``account_info().trade_mode`` is 0 for a demo account (``ACCOUNT_TRADE_MODE_DEMO``); login,
  server, equity, margin and leverage come from ``fake.account`` (a dict a test may edit);
- ``order_send`` handles ``TRADE_ACTION_DEAL`` (open, or close/reduce when the request carries
  a ``position`` ticket), ``TRADE_ACTION_PENDING`` and ``TRADE_ACTION_REMOVE``, keeps
  ``positions_get`` / ``orders_get`` consistent, validates the volume against
  ``volume_min`` / ``volume_step`` / ``volume_max`` (``TRADE_RETCODE_INVALID_VOLUME``) and can
  be scripted through ``fake.scripted_results`` (a queue of dicts: ``retcode``, ``volume``,
  ``price``, ``comment`` or ``none: True`` for a ``None`` result) to replay a partial fill, a
  requote or a rejection; every request is recorded in ``calls``;
- ``order_calc_margin`` returns ``fake.margin_per_lot[name] x volume`` (or notional /
  leverage) in the account currency, ``None`` for an unknown symbol;
- ``symbol_info_tick`` quotes ``fake.quotes[name] = (bid, ask)``;
- ``initialize`` / ``shutdown`` / ``last_error`` / ``terminal_info`` / ``symbol_select``
  / ``symbols_get`` behave like the real ones, and every call is recorded in ``calls``.

Bars are generated by :func:`synthetic_rates`: weekday server days for D1, contiguous
intraday bars for H4/H1, a deterministic random walk from a seed. Nothing here looks like
a real market; it only has to have the right shape.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from types import SimpleNamespace
from typing import Any

import numpy as np

# The real constants, so code that reads ``mt5.TIMEFRAME_D1`` works against the fake.
TIMEFRAME_M1 = 1
TIMEFRAME_M15 = 15
TIMEFRAME_H1 = 16385
TIMEFRAME_H4 = 16388
TIMEFRAME_D1 = 16408
ACCOUNT_TRADE_MODE_DEMO = 0
ACCOUNT_TRADE_MODE_CONTEST = 1
ACCOUNT_TRADE_MODE_REAL = 2
SYMBOL_TRADE_MODE_FULL = 4
TRADE_ACTION_DEAL = 1
TRADE_ACTION_PENDING = 5
TRADE_ACTION_SLTP = 6
TRADE_ACTION_MODIFY = 7
TRADE_ACTION_REMOVE = 8
ORDER_TYPE_BUY = 0
ORDER_TYPE_SELL = 1
ORDER_TYPE_BUY_LIMIT = 2
ORDER_TYPE_SELL_LIMIT = 3
ORDER_TYPE_BUY_STOP = 4
ORDER_TYPE_SELL_STOP = 5
ORDER_TIME_GTC = 0
ORDER_FILLING_FOK = 0
ORDER_FILLING_IOC = 1
ORDER_FILLING_RETURN = 2
POSITION_TYPE_BUY = 0
POSITION_TYPE_SELL = 1
TRADE_RETCODE_REQUOTE = 10004
TRADE_RETCODE_REJECT = 10006
TRADE_RETCODE_PLACED = 10008
TRADE_RETCODE_DONE = 10009
TRADE_RETCODE_DONE_PARTIAL = 10010
TRADE_RETCODE_INVALID = 10013
TRADE_RETCODE_INVALID_VOLUME = 10014
TRADE_RETCODE_INVALID_PRICE = 10015
TRADE_RETCODE_MARKET_CLOSED = 10018
TRADE_RETCODE_NO_MONEY = 10019
TRADE_RETCODE_PRICE_CHANGED = 10020
TRADE_RETCODE_CLIENT_DISABLES_AT = 10027
TRADE_CONSTANTS = {
    name: value
    for name, value in dict(globals()).items()
    if name.startswith(
        ("TRADE_ACTION_", "ORDER_TYPE_", "ORDER_TIME_", "ORDER_FILLING_", "POSITION_TYPE_", "TRADE_RETCODE_")
    )
}

RATES_DTYPE = np.dtype(
    [
        ("time", "<i8"),
        ("open", "<f8"),
        ("high", "<f8"),
        ("low", "<f8"),
        ("close", "<f8"),
        ("tick_volume", "<u8"),
        ("spread", "<i4"),
        ("real_volume", "<u8"),
    ]
)

TICKS_DTYPE = np.dtype(
    [
        ("time", "<i8"),
        ("bid", "<f8"),
        ("ask", "<f8"),
        ("last", "<f8"),
        ("volume", "<u8"),
        ("time_msc", "<i8"),
        ("flags", "<u4"),
        ("volume_real", "<f8"),
    ]
)


def synthetic_ticks(
    start_server: datetime,
    n_ticks: int,
    *,
    step_seconds: int = 60,
    mid: float = 1.1,
    spread: float = 0.00008,
    spread_by_hour: dict[int, float] | None = None,
) -> np.ndarray:
    """``n_ticks`` ticks every ``step_seconds`` from ``start_server`` (naive server clock).

    ``spread_by_hour`` overrides the quoted spread for the given server-clock hours, which is
    how a test plants a wide spread in one session and a narrow one elsewhere.
    """
    rows = []
    cursor = start_server
    for _ in range(n_ticks):
        sp = (spread_by_hour or {}).get(cursor.hour, spread)
        epoch = _server_epoch(cursor)
        rows.append((epoch, mid - sp / 2, mid + sp / 2, 0.0, 0, epoch * 1000, 6, 0.0))
        cursor += timedelta(seconds=step_seconds)
    return np.array(rows, dtype=TICKS_DTYPE)


TIMEFRAME_MINUTES = {
    TIMEFRAME_M1: 1,
    TIMEFRAME_M15: 15,
    TIMEFRAME_H1: 60,
    TIMEFRAME_H4: 240,
    TIMEFRAME_D1: 1440,
}


def _server_epoch(server_naive: datetime) -> int:
    """Server-clock reading -> the epoch MT5 reports (server time read as if UTC)."""
    return int(server_naive.replace(tzinfo=UTC).timestamp())


def synthetic_rates(
    start_server: datetime,
    n_bars: int,
    timeframe: int,
    *,
    seed: int = 0,
    price: float = 1.1,
    spread_points: int = 12,
    skip_weekends: bool = True,
) -> np.ndarray:
    """``n_bars`` bars from ``start_server`` (naive server clock), as ``copy_rates_range`` returns.

    D1 bars step one server day and skip Saturday/Sunday when ``skip_weekends``; intraday
    bars step ``TIMEFRAME_MINUTES[timeframe]`` and skip bars that open on a Saturday or on a
    Sunday, which is roughly what an FX symbol prints on a server whose day boundary is the
    New York close.
    """
    rng = np.random.default_rng(seed)
    step = timedelta(minutes=TIMEFRAME_MINUTES[timeframe])
    rows: list[tuple] = []
    cursor = start_server
    level = price
    while len(rows) < n_bars:
        if skip_weekends and cursor.weekday() >= 5:
            cursor += step
            continue
        ret = rng.normal(0, 0.003)
        o = level
        c = level * (1 + ret)
        hi = max(o, c) * (1 + abs(rng.normal(0, 0.001)))
        lo = min(o, c) * (1 - abs(rng.normal(0, 0.001)))
        rows.append(
            (
                _server_epoch(cursor),
                o,
                hi,
                lo,
                c,
                int(rng.integers(500, 5000)),
                int(spread_points + rng.integers(-3, 4)),
                0,
            )
        )
        level = c
        cursor += step
    return np.array(rows, dtype=RATES_DTYPE)


def default_symbol_info(name: str, **overrides: Any) -> SimpleNamespace:
    jpy = "JPY" in name
    info = dict(
        name=name,
        path=f"Forex\\Majors\\{name}",
        description=f"{name[:3]} vs {name[3:6]}",
        trade_contract_size=100_000.0,
        volume_min=0.01,
        volume_step=0.01,
        volume_max=200.0,
        digits=3 if jpy else 5,
        point=0.001 if jpy else 0.00001,
        swap_mode=1,
        swap_long=-5.2,
        swap_short=1.1,
        swap_rollover3days=3,  # Wednesday
        trade_mode=SYMBOL_TRADE_MODE_FULL,
        currency_base=name[:3],
        currency_profit=name[3:6],
        currency_margin=name[:3],
        visible=True,
    )
    info.update(overrides)
    return SimpleNamespace(**info)


class FakeMT5:
    """Stand-in for the ``MetaTrader5`` module.

    ``rates`` maps ``(market_watch_name, timeframe_constant)`` to a structured array and is what
    ``copy_rates_range`` serves. ``deep_rates`` (optional, same shape) is what ``copy_rates_from``
    serves instead when set, so a test can reproduce a terminal whose chart cache is shallower
    than the server's history. ``server_offset_minutes`` is the server clock minus UTC used by
    ``symbol_info_tick``.
    """

    TIMEFRAME_M1 = TIMEFRAME_M1
    TIMEFRAME_M15 = TIMEFRAME_M15
    TIMEFRAME_H1 = TIMEFRAME_H1
    TIMEFRAME_H4 = TIMEFRAME_H4
    TIMEFRAME_D1 = TIMEFRAME_D1
    ACCOUNT_TRADE_MODE_DEMO = ACCOUNT_TRADE_MODE_DEMO
    ACCOUNT_TRADE_MODE_CONTEST = ACCOUNT_TRADE_MODE_CONTEST
    ACCOUNT_TRADE_MODE_REAL = ACCOUNT_TRADE_MODE_REAL
    locals().update(TRADE_CONSTANTS)  # TRADE_ACTION_*, ORDER_TYPE_*, TRADE_RETCODE_*, ...

    def __init__(
        self,
        rates: dict[tuple[str, int], np.ndarray] | None = None,
        *,
        deep_rates: dict[tuple[str, int], np.ndarray] | None = None,
        symbols: dict[str, SimpleNamespace] | None = None,
        server_offset_minutes: int = 0,
        now_utc: datetime | None = None,
        account_trade_mode: int = ACCOUNT_TRADE_MODE_DEMO,
        server_name: str = "Exness-MT5Trial",
        fail_initialize: bool = False,
    ) -> None:
        self.rates = dict(rates or {})
        # What a COUNT-based request (``copy_rates_from``) returns when it differs from what the
        # terminal has already synchronised. Empty by default: both paths then see one history.
        self.deep_rates: dict[tuple[str, int], np.ndarray] = dict(deep_rates or {})
        names = {name for name, _ in self.rates}
        self.symbols = dict(symbols or {})
        for name in names:
            self.symbols.setdefault(name, default_symbol_info(name))
        self.server_offset_minutes = server_offset_minutes
        self.now_utc = now_utc or datetime.now(UTC)  # a tick is 'now' unless a test pins it
        self.account_trade_mode = account_trade_mode
        self.server_name = server_name
        self.fail_initialize = fail_initialize
        self.initialized = False
        self.calls: list[tuple[str, tuple, dict]] = []
        self._error: tuple[int, str] = (1, "Success")
        # -- trading state (broker adapter tests) --
        self.account: dict[str, Any] = {
            "login": 12345678,
            "balance": 10_000.0,
            "equity": 10_000.0,
            "margin": 0.0,
            "leverage": 100,
            "currency": "USD",
            "name": "Fake Trader",
            "company": "Fake Broker",
        }
        self.quotes: dict[str, tuple[float, float]] = {}  # name -> (bid, ask); default 1.1 / 1.10012
        self.positions: dict[int, SimpleNamespace] = {}
        self.orders: dict[int, SimpleNamespace] = {}
        self.deals: list[SimpleNamespace] = []
        self.scripted_results: list[dict[str, Any]] = []
        self.margin_per_lot: dict[str, float] = {}
        self.connected = True  # terminal_info().connected; a test flips it to simulate a drop
        self._next_ticket = 1000

    # -- bookkeeping -----------------------------------------------------------------
    def _record(self, name: str, *args: Any, **kwargs: Any) -> None:
        self.calls.append((name, args, kwargs))

    def last_error(self) -> tuple[int, str]:
        return self._error

    # -- connection -----------------------------------------------------------------
    def initialize(self, *args: Any, **kwargs: Any) -> bool:
        self._record("initialize", *args, **kwargs)
        if self.fail_initialize:
            self._error = (-10005, "IPC timeout")
            return False
        self.initialized = True
        return True

    def login(self, *args: Any, **kwargs: Any) -> bool:
        self._record("login", *args, **kwargs)
        return True

    def shutdown(self) -> None:
        self._record("shutdown")
        self.initialized = False

    def terminal_info(self) -> SimpleNamespace | None:
        if not self.initialized:
            return None
        return SimpleNamespace(
            connected=self.connected,
            name="MetaTrader 5",
            company="Fake",
            path="C:\\fake",
            build=4620,
            trade_allowed=True,
            maxbars=100_000,
        )

    def account_info(self) -> SimpleNamespace | None:
        if not self.initialized:
            return None
        a = self.account
        return SimpleNamespace(
            login=a["login"],
            trade_mode=self.account_trade_mode,
            server=self.server_name,
            currency=a["currency"],
            balance=a["balance"],
            equity=a["equity"],
            margin=a["margin"],
            margin_free=a["equity"] - a["margin"],
            leverage=a["leverage"],
            name=a["name"],
            company=a["company"],
            profit=a["equity"] - a["balance"],
            trade_allowed=True,
        )

    # -- symbols --------------------------------------------------------------------
    def symbols_get(self, group: str | None = None) -> tuple[SimpleNamespace, ...]:
        self._record("symbols_get", group)
        return tuple(self.symbols.values())

    def symbol_info(self, name: str) -> SimpleNamespace | None:
        self._record("symbol_info", name)
        return self.symbols.get(name)

    def symbol_select(self, name: str, enable: bool = True) -> bool:
        self._record("symbol_select", name, enable)
        return name in self.symbols

    def symbol_info_tick(self, name: str) -> SimpleNamespace | None:
        self._record("symbol_info_tick", name)
        if name not in self.symbols:
            return None
        server_now = (self.now_utc + timedelta(minutes=self.server_offset_minutes)).replace(
            tzinfo=None
        )
        bid, ask = self.quotes.get(name, (1.1, 1.10012))
        return SimpleNamespace(
            time=_server_epoch(server_now),
            bid=bid,
            ask=ask,
            last=0.0,
            volume=0,
            time_msc=_server_epoch(server_now) * 1000,
        )

    # -- trading ----------------------------------------------------------------------
    def _server_now_epoch(self) -> int:
        server_now = (self.now_utc + timedelta(minutes=self.server_offset_minutes)).replace(tzinfo=None)
        return _server_epoch(server_now)

    def _result(self, retcode: int, **fields: Any) -> SimpleNamespace:
        base = dict(
            retcode=retcode,
            deal=0,
            order=0,
            volume=0.0,
            price=0.0,
            bid=0.0,
            ask=0.0,
            comment="",
            request_id=len(self.calls),
            retcode_external=0,
        )
        base.update(fields)
        return SimpleNamespace(**base)

    def _volume_ok(self, info: SimpleNamespace, volume: float) -> bool:
        if volume < info.volume_min - 1e-12 or volume > info.volume_max + 1e-12:
            return False
        steps = volume / info.volume_step
        return abs(steps - round(steps)) < 1e-6

    def order_send(self, request: dict[str, Any]) -> SimpleNamespace | None:
        """``TRADE_ACTION_DEAL`` / ``PENDING`` / ``REMOVE`` against the in-memory book."""
        self._record("order_send", dict(request))
        scripted = self.scripted_results.pop(0) if self.scripted_results else None
        if scripted and scripted.get("none"):
            self._error = (-10004, "No IPC connection")
            return None
        action = request.get("action")
        if action == TRADE_ACTION_REMOVE:
            ticket = int(request.get("order", 0))
            if ticket not in self.orders:
                return self._result(TRADE_RETCODE_INVALID, comment="Invalid request")
            del self.orders[ticket]
            return self._result(TRADE_RETCODE_DONE, order=ticket, comment="Request executed")

        name = request.get("symbol")
        info = self.symbols.get(name)
        if info is None:
            return self._result(TRADE_RETCODE_INVALID, comment="Unknown symbol")
        volume = float(request.get("volume", 0.0))
        if not self._volume_ok(info, volume):
            return self._result(TRADE_RETCODE_INVALID_VOLUME, comment="Invalid volume")
        if scripted and scripted.get("retcode", TRADE_RETCODE_DONE) not in (
            TRADE_RETCODE_DONE,
            TRADE_RETCODE_DONE_PARTIAL,
            TRADE_RETCODE_PLACED,
        ):
            return self._result(scripted["retcode"], comment=scripted.get("comment", "scripted"))

        if action == TRADE_ACTION_PENDING:
            ticket = self._next_ticket
            self._next_ticket += 1
            self.orders[ticket] = SimpleNamespace(
                ticket=ticket,
                symbol=name,
                type=request["type"],
                volume_initial=volume,
                volume_current=volume,
                price_open=float(request.get("price", 0.0)),
                sl=float(request.get("sl", 0.0) or 0.0),
                tp=float(request.get("tp", 0.0) or 0.0),
                magic=int(request.get("magic", 0)),
                comment=request.get("comment", ""),
                time_setup=self._server_now_epoch(),
                state=1,
            )
            return self._result(TRADE_RETCODE_PLACED, order=ticket, volume=volume, comment="Order placed")

        if action != TRADE_ACTION_DEAL:
            return self._result(TRADE_RETCODE_INVALID, comment="Unsupported action")

        retcode = scripted.get("retcode", TRADE_RETCODE_DONE) if scripted else TRADE_RETCODE_DONE
        fill_volume = float(scripted.get("volume", volume)) if scripted else volume
        if fill_volume < volume - 1e-12:
            retcode = TRADE_RETCODE_DONE_PARTIAL
        bid, ask = self.quotes.get(name, (1.1, 1.10012))
        requested_price = float(request.get("price", 0.0))
        fill_price = float(scripted.get("price", requested_price)) if scripted else requested_price
        deal = self._next_ticket
        self._next_ticket += 1
        order_ticket = self._next_ticket
        self._next_ticket += 1
        position_ticket = request.get("position")
        if position_ticket is not None:
            pos = self.positions.get(int(position_ticket))
            if pos is None:
                return self._result(TRADE_RETCODE_INVALID, comment="Position not found")
            pos.volume = round(pos.volume - fill_volume, 8)
            if pos.volume <= 1e-9:
                del self.positions[int(position_ticket)]
            self.deals.append(
                SimpleNamespace(
                    ticket=deal, order=order_ticket, position_id=int(position_ticket),
                    symbol=name, volume=fill_volume, price=fill_price, entry=1,
                )
            )
        else:
            self.positions[order_ticket] = SimpleNamespace(
                ticket=order_ticket,
                identifier=order_ticket,
                symbol=name,
                type=POSITION_TYPE_BUY if request["type"] == ORDER_TYPE_BUY else POSITION_TYPE_SELL,
                volume=fill_volume,
                price_open=fill_price,
                price_current=fill_price,
                sl=float(request.get("sl", 0.0) or 0.0),
                tp=float(request.get("tp", 0.0) or 0.0),
                profit=0.0,
                swap=0.0,
                magic=int(request.get("magic", 0)),
                comment=request.get("comment", ""),
                time=self._server_now_epoch(),
                time_msc=self._server_now_epoch() * 1000,
            )
            self.deals.append(
                SimpleNamespace(
                    ticket=deal, order=order_ticket, position_id=order_ticket,
                    symbol=name, volume=fill_volume, price=fill_price, entry=0,
                )
            )
        return self._result(
            retcode,
            deal=deal,
            order=order_ticket,
            volume=fill_volume,
            price=fill_price,
            bid=bid,
            ask=ask,
            comment="Request executed" if retcode == TRADE_RETCODE_DONE else "Partial fill",
        )

    def positions_get(
        self, symbol: str | None = None, group: str | None = None, ticket: int | None = None
    ) -> tuple[SimpleNamespace, ...]:
        self._record("positions_get", symbol, group, ticket)
        items = list(self.positions.values())
        if ticket is not None:
            items = [p for p in items if p.ticket == ticket]
        if symbol is not None:
            items = [p for p in items if p.symbol == symbol]
        return tuple(items)

    def orders_get(
        self, symbol: str | None = None, group: str | None = None, ticket: int | None = None
    ) -> tuple[SimpleNamespace, ...]:
        self._record("orders_get", symbol, group, ticket)
        items = list(self.orders.values())
        if ticket is not None:
            items = [o for o in items if o.ticket == ticket]
        if symbol is not None:
            items = [o for o in items if o.symbol == symbol]
        return tuple(items)

    def order_calc_margin(self, action_type: int, symbol: str, volume: float, price: float) -> float | None:
        self._record("order_calc_margin", action_type, symbol, volume, price)
        info = self.symbols.get(symbol)
        if info is None:
            return None
        per_lot = self.margin_per_lot.get(symbol)
        if per_lot is None:
            per_lot = info.trade_contract_size * float(price) / float(self.account["leverage"])
        return float(per_lot * volume)

    def order_check(self, request: dict[str, Any]) -> SimpleNamespace:
        self._record("order_check", dict(request))
        return self._result(0, comment="Done")

    # -- history --------------------------------------------------------------------
    COPY_TICKS_INFO = 1

    def copy_ticks_range(
        self, name: str, date_from: datetime, date_to: datetime, flags: int = 1
    ) -> np.ndarray | None:
        """Ticks from ``self.ticks[name]`` (a ``TICKS_DTYPE`` array) inside the server window."""
        self._record("copy_ticks_range", name, date_from, date_to, flags)
        arr = getattr(self, "ticks", {}).get(name)
        if arr is None:
            self._error = (-2, "Terminal: Invalid params")
            return None
        lo = _server_epoch(date_from.replace(tzinfo=None)) * 1000
        hi = _server_epoch(date_to.replace(tzinfo=None)) * 1000
        return arr[(arr["time_msc"] >= lo) & (arr["time_msc"] < hi)]

    @staticmethod
    def _as_epoch(value: datetime | int | float) -> int:
        """``copy_rates_*`` accepts a naive server ``datetime`` or epoch seconds; take both."""
        if isinstance(value, datetime):
            return _server_epoch(value.replace(tzinfo=None))
        return int(value)

    def copy_rates_range(
        self, name: str, timeframe: int, date_from: datetime | int, date_to: datetime | int
    ) -> np.ndarray | None:
        self._record("copy_rates_range", name, timeframe, date_from, date_to)
        arr = self.rates.get((name, timeframe))
        if arr is None:
            self._error = (-2, "Terminal: Invalid params")
            return None
        lo = self._as_epoch(date_from)
        hi = self._as_epoch(date_to)
        return arr[(arr["time"] >= lo) & (arr["time"] <= hi)]

    def copy_rates_from(
        self, name: str, timeframe: int, date_from: datetime | int, count: int
    ) -> np.ndarray | None:
        """The ``count`` bars ending at ``date_from``, oldest first — MT5's own ordering.

        Reads ``self.deep_rates`` when the test set one, else ``self.rates``. The two exist
        because the real terminal answers a count request from the *server* and a range request
        from the bars it has already synchronised, which is the whole reason
        ``mt5_loader._copy_rates_deep`` exists (measured on XAUUSD H1, 2026-09-07: 2017-03 by
        count against 2022-10 by range on the same login, minutes apart).
        """
        self._record("copy_rates_from", name, timeframe, date_from, count)
        arr = getattr(self, "deep_rates", {}).get((name, timeframe))
        if arr is None:
            arr = self.rates.get((name, timeframe))
        if arr is None:
            self._error = (-2, "Terminal: Invalid params")
            return None
        upto = arr[arr["time"] <= self._as_epoch(date_from)]
        if len(upto) == 0:
            return upto
        return upto[-int(count) :]


def make_fake(
    symbols: list[str],
    *,
    timeframes: tuple[int, ...] = (TIMEFRAME_D1, TIMEFRAME_H4, TIMEFRAME_H1),
    start_server: datetime = datetime(2024, 1, 1),
    n_days: int = 60,
    server_offset_minutes: int = 120,
    suffix: str = "",
    **kwargs: Any,
) -> FakeMT5:
    """A fake with ``n_days`` weekdays of D1 and the matching H4/H1 bars for ``symbols``."""
    rates: dict[tuple[str, int], np.ndarray] = {}
    for i, bare in enumerate(symbols):
        name = f"{bare}{suffix}"
        for tf in timeframes:
            per_day = 1440 // TIMEFRAME_MINUTES[tf]
            rates[(name, tf)] = synthetic_rates(
                start_server, n_days * per_day, tf, seed=i * 10 + tf, price=1.0 + 0.1 * i
            )
    return FakeMT5(rates, server_offset_minutes=server_offset_minutes, **kwargs)


__all__ = [
    "ACCOUNT_TRADE_MODE_DEMO",
    "ACCOUNT_TRADE_MODE_REAL",
    "RATES_DTYPE",
    "TICKS_DTYPE",
    "TIMEFRAME_D1",
    "TIMEFRAME_H1",
    "TIMEFRAME_H4",
    "TIMEFRAME_MINUTES",
    "TRADE_CONSTANTS",
    "FakeMT5",
    "default_symbol_info",
    "make_fake",
    "synthetic_rates",
    "synthetic_ticks",
]
