"""HTML report renderer with template support."""

from __future__ import annotations

from typing import Any

from ml4t.diagnostic.reporting.base import ReportFormat, ReportGenerator
from ml4t.diagnostic.results.base import BaseResult


class HTMLReportGenerator(ReportGenerator):
    """Generate HTML reports from evaluation results.

    Supports custom templates and styling.

    Examples:
        >>> generator = HTMLReportGenerator()
        >>> report = generator.render(result, template="default")
        >>> generator.save(report, "report.html")

        >>> # Custom template
        >>> custom_template = '''
        ... <html><body>
        ... <h1>{analysis_type}</h1>
        ... {content}
        ... </body></html>
        ... '''
        >>> report = generator.render(result, custom_template=custom_template)
    """

    DEFAULT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #FAFAF9;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(10,22,40,0.08);
        }}
        h1 {{
            color: #0a1628;
            border-bottom: 2px solid #D4A84B;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #1a2d4a;
            margin-top: 30px;
        }}
        .metadata {{
            background-color: #F8F8F6;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }}
        .metadata-item {{
            margin: 5px 0;
        }}
        .summary {{
            background-color: #fffbf0;
            border-left: 4px solid #D4A84B;
            padding: 15px;
            margin: 20px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th {{
            background-color: #0a1628;
            color: #F8F8F6;
            padding: 12px;
            text-align: left;
        }}
        td {{
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        {metadata}
        {summary}
        {dataframes}
        <div class="footer">
            Generated by ML4T Diagnostic {version}
        </div>
    </div>
</body>
</html>"""

    def render(self, result: BaseResult, **options: Any) -> str:
        """Render result to HTML format.

        Args:
            result: Evaluation result to render
            **options: HTML rendering options
                - template: Template name or "default" (default: "default")
                - custom_template: Custom HTML template string
                - include_metadata: Include metadata section (default: True)
                - include_dataframes: Include DataFrame tables (default: True)
                - max_rows: Max rows to show in DataFrame tables (default: 50)

        Returns:
            HTML string
        """
        template = options.get("custom_template") or self.DEFAULT_TEMPLATE
        include_metadata = options.get("include_metadata", True)
        include_dataframes = options.get("include_dataframes", True)
        max_rows = options.get("max_rows", 50)

        # Build template variables
        analysis_type = result.analysis_type.replace("_", " ").title()
        title = f"{analysis_type} Report"

        # Metadata section
        metadata_html = ""
        if include_metadata:
            metadata_html = f"""
            <div class="metadata">
                <h2>Metadata</h2>
                <div class="metadata-item"><strong>Analysis Type:</strong> {result.analysis_type}</div>
                <div class="metadata-item"><strong>Created:</strong> {result.created_at}</div>
                <div class="metadata-item"><strong>ML4T Diagnostic Version:</strong> {result.version}</div>
            </div>
            """

        # Summary section
        summary_html = f"""
        <div class="summary">
            <h2>Summary</h2>
            <pre>{self._escape_html(result.summary())}</pre>
        </div>
        """

        # DataFrame sections
        dataframes_html = ""
        if include_dataframes:
            try:
                available_dfs = result.list_available_dataframes()
                if available_dfs:
                    df_sections = []
                    for df_name in available_dfs:
                        df = result.get_dataframe(df_name)

                        # Limit rows if needed
                        if len(df) > max_rows:
                            display_df = df.head(max_rows)
                            caption = f"Showing first {max_rows} of {len(df)} rows"
                        else:
                            display_df = df
                            caption = ""

                        table_html = self._dataframe_to_html(
                            display_df, title=df_name.replace("_", " ").title(), caption=caption
                        )
                        df_sections.append(table_html)

                    dataframes_html = "\n".join(df_sections)
            except (NotImplementedError, ValueError):
                # Some results may not have DataFrames
                pass

        # Fill template
        html = template.format(
            title=title,
            analysis_type=analysis_type,
            metadata=metadata_html,
            summary=summary_html,
            dataframes=dataframes_html,
            version=result.version,
        )

        return html

    def _dataframe_to_html(self, df, title: str = "", caption: str = "") -> str:
        """Convert Polars DataFrame to HTML table.

        Args:
            df: Polars DataFrame
            title: Table title
            caption: Optional caption

        Returns:
            HTML table string
        """
        html_parts = []

        if title:
            html_parts.append(f"<h2>{title}</h2>")

        if caption:
            html_parts.append(f"<p><em>{caption}</em></p>")

        # Table header
        html_parts.append("<table>")
        html_parts.append("<thead><tr>")
        for col in df.columns:
            html_parts.append(f"<th>{self._escape_html(col)}</th>")
        html_parts.append("</tr></thead>")

        # Table body
        html_parts.append("<tbody>")
        for row in df.iter_rows():
            html_parts.append("<tr>")
            for val in row:
                formatted = self._format_cell(val)
                html_parts.append(f"<td>{formatted}</td>")
            html_parts.append("</tr>")
        html_parts.append("</tbody>")
        html_parts.append("</table>")

        return "\n".join(html_parts)

    def _format_cell(self, value: Any) -> str:
        """Format cell value for HTML display.

        Args:
            value: Cell value

        Returns:
            Formatted HTML string
        """
        if value is None:
            return "<em>null</em>"
        elif isinstance(value, float):
            return f"{value:.4f}"
        else:
            return self._escape_html(str(value))

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters.

        Args:
            text: Text to escape

        Returns:
            Escaped text
        """
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )


# Register with factory
from ml4t.diagnostic.reporting.base import ReportFactory  # noqa: E402

ReportFactory.register(ReportFormat.HTML, HTMLReportGenerator)
